workspace(name = "Advent_of_Code")

local_repository(
    name = "aoc",
    path = ".",
)

# External rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "52c5ab0b68841b96463e1bd44760ef2bbbffa0804873496b6e0f982f5b3176f6",
    strip_prefix = "rules_nixpkgs-acb9e36f403ec6f38bac81290781cb896f22a85e",  # 2020-11-30
    urls = [
        "https://github.com/tweag/rules_nixpkgs/archive/acb9e36f403ec6f38bac81290781cb896f22a85e.tar.gz",
    ],
)

http_archive(
    name = "rules_haskell",
    sha256 = "dcdbe556c3b30a3724496694626734bb3382f210480833e314ff3d9c6cfda95c",
    strip_prefix = "rules_haskell-f69edf3786e0f48fc004b1dfda2c25ab346e8afe",  # 2020-12-18
    urls = [
        "https://github.com/tweag/rules_haskell/archive/f69edf3786e0f48fc004b1dfda2c25ab346e8afe.tar.gz",
    ],
)

http_archive(
    name = "io_bazel_rules_rust",
    sha256 = "bbebfd5b292fa8567fa012b3d1056f2e51611fe8ac898860323b6b4d763a4efd",
    strip_prefix = "rules_rust-c7a408a8c58c6dde73a552d6f78f90c7ef96b513",  # 2020-12-22
    urls = [
        "https://github.com/bazelbuild/rules_rust/archive/c7a408a8c58c6dde73a552d6f78f90c7ef96b513.tar.gz",
    ],
)

load("@rules_haskell//haskell:repositories.bzl", "rules_haskell_dependencies")

rules_haskell_dependencies()

# Setup Nix
load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")

rules_nixpkgs_dependencies()

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_cc_configure",
    "nixpkgs_git_repository",
    "nixpkgs_package",
    "nixpkgs_python_configure",
)

nixpkgs_git_repository(
    name = "nixpkgs_default",
    revision = "ca119749d86f484066fae7680af8a44ea1f11ca8",  # NixOS/nixpkgs@nixos-20.09, 2020-12-24
)

nixpkgs_cc_configure(
    nix_file = "@rules_haskell//nixpkgs:cc-toolchain.nix",
    nix_file_deps = ["@rules_haskell//nixpkgs:default.nix"],
    repository = "@rules_haskell//nixpkgs:default.nix",
)

nixpkgs_python_configure(
    repository = "@rules_haskell//nixpkgs:default.nix",
)

# Use GHC binaries from nixpkgs (NixOS)
load("@rules_haskell//haskell:nixpkgs.bzl", "haskell_register_ghc_nixpkgs")

haskell_register_ghc_nixpkgs(
    attribute_path = "haskell.compiler.ghc8102",
    repositories = {"nixpkgs": "@nixpkgs_default"},
    version = "8.10.2",
)

## ghcide
nixpkgs_package(
    name = "ghcide",
    attribute_path = "haskellPackages.ghcide",
    repository = "@nixpkgs_default",
)

# Setup Rust compiler through Nix
http_archive(
    name = "nixpkgs-mozilla",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "out",
    srcs = ["**"],
)
    """,
    sha256 = "1f69a63766156c0396390212b7c5ecd2941b424ae68e1f25a2c30c8416af7d03",
    strip_prefix = "nixpkgs-mozilla-8c007b60731c07dd7a052cce508de3bb1ae849b4",  # 2020-10-28
    urls = [
        "https://github.com/mozilla/nixpkgs-mozilla/archive/8c007b60731c07dd7a052cce508de3bb1ae849b4.tar.gz",
    ],
)

nixpkgs_package(
    name = "rust_default",
    attribute_path = "rust",
    build_file_content = """
# Adopted from https://github.com/tweag/rules_nixpkgs/blob/ad6db1389261a2bbfca69b2edc206a48cd558919/nixpkgs/BUILD.pkg
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "bin",
    srcs = glob(["bin/*"], allow_empty = True),
)

# Adopted from https://github.com/bazelbuild/rules_rust/blob/67f0c5ec0397d24ccc14264a0eda86915ddf63e8/rust/repositories.bzl#L273
filegroup(
    name = "rust_lib",
    srcs = glob([
        "lib/rustlib/*/lib/*",
    ], allow_empty = True)
)

# Adopted from https://github.com/bazelbuild/rules_rust/blob/67f0c5ec0397d24ccc14264a0eda86915ddf63e8/rust/repositories.bzl#L182
filegroup(
    name = "rustc_lib",
    srcs = glob([
        "lib/*",
        "lib/rustlib/*/codegen-backends/*",
        "lib/rustlib/*/bin/rust-lld*",
        "lib/rustlib/*/lib/*",
    ], allow_empty = True)
)
    """,
    nix_file_content = """
let
  nixpkgs = import <nixpkgs> { overlays = [ (import <rust-overlay>) ]; };
in
(nixpkgs.rustChannelOf { channel = "1.48.0"; })
    """,
    repositories = {
        "nixpkgs": "@nixpkgs_default",
        "rust-overlay": "@nixpkgs-mozilla//:rust-overlay.nix",
    },
)

register_toolchains(
    "//:rust_toolchain",
)
